name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalação do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalação das dependências
        run: npm install

      - name: Compilar TypeScript
        run: npx tsc

      - name: Selecionar testes impactados
        id: select-tests
        run: |
          TESTS=$(node dist/scripts/select-tests.js)
          echo "tests=$TESTS" >> $GITHUB_ENV

      - name: Rodar Testes do Cypress
        run: npx cypress run --spec "$tests"

      - name: Salvar vídeos do Cypress
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

  notifications:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Envio de notificação de sucesso
        if: success()
        run: echo "✅ Todos os testes passaram!" >> $GITHUB_STEP_SUMMARY

      - name: Envio de notificação de falha
        if: failure()
        run: echo "❌ Algum teste falhou! Verifique os relatórios." >> $GITHUB_STEP_SUMMARY
