name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Garante histórico completo para o git diff

      - name: Instalação do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalação das dependências
        run: |
          npm install

      - name: Compilar TypeScript
        run: |
          npx tsc

      - name: Selecionar testes impactados
        run: |
          TESTS=$(node dist/scripts/select-tests.js)
          echo "TESTS=$TESTS" >> $GITHUB_ENV

      - name: Rodar Testes do Cypress
        run: |
          echo "Rodando testes: $TESTS"
          npx cypress run --spec "$TESTS"

      - name: Salvar vídeos do Cypress
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

  notifications:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Envio de notificação de sucesso
        if: success()
        run: echo "✅ Todos os testes passaram!" >> $GITHUB_STEP_SUMMARY

      - name: Envio de notificação de falha
        if: failure()
        run: echo "❌ Algum teste falhou! Verifique os relatórios." >> $GITHUB_STEP_SUMMARY
