name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Checkout Cypress-Auto repository
        uses: actions/checkout@v3
        with:
          repository: betogouvea/Cypress-Auto
          path: Cypress-Auto

      - name: Instalação do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalação das dependências
        run: |
          cd Cypress-Auto
          npm ci

      # Se você quiser compilar antes (opcional, caso seu projeto precise):
      # - name: Compilar TypeScript
      #   run: |
      #     cd Cypress-Auto
      #     npx tsc

      - name: Rodar Testes do Cypress
        run: |
          cd Cypress-Auto
          npx cypress run

      - name: Salvar vídeos do Cypress
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: Cypress-Auto/cypress/videos

  notifications:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Envio de notificação de sucesso
        if: success()
        run: echo "✅ Todos os testes passaram!" >> $GITHUB_STEP_SUMMARY

      - name: Envio de notificação de falha
        if: failure()
        run: echo "❌ Algum teste falhou! Verifique os relatórios." >> $GITHUB_STEP_SUMMARY

