name: Postman Tests

on:
  workflow_dispatch: 

jobs:
  postman_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Checkout Postman-API repository
        uses: actions/checkout@v3
        with:
          repository: betogouvea/Postman-API
          path: Postman-API

      - name: Instalação do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalação do Newman (CLI do Postman)
        run: npm install -g newman

      - name: Rodar Testes do Postman
        run: newman run Postman-API/postman-tests/collection.json 

      - name: Salvar relatório do Postman
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-reports
          path: Postman-API
  notifications:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Envio de notificação de sucesso
        if: success()
        run: echo "✅ Todos os testes passaram!" >> $GITHUB_STEP_SUMMARY

      - name: Envio de notificação de falha
        if: failure()
        run: echo "❌ Algum teste falhou! Verifique os relatórios." >> $GITHUB_STEP_SUMMARY
